server {
    listen       80;
    server_name  localhost;
    root         /usr/share/nginx/html;
    index        index.html;

    # Compression
    gzip              on;
    gzip_vary         on;
    gzip_comp_level   6;
    gzip_min_length   256;
    gzip_types        text/plain text/css application/javascript image/svg+xml application/json application/xml;

    # Types explicites (SVG + favicon)
    location ~* \.svg$ {
        add_header Content-Type image/svg+xml;
    }

    # Pas de cache en dev: on veut toujours voir les dernières modifs
    location /assets/ {
        expires -1;
        add_header Cache-Control "no-store, must-revalidate";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
